### ISSUE TITLE
PictureSign removes the "Edit Sign" keybind in MultiMC

### ISSUE THREAD

**Issue by MisterVideosoEx** [TeamMidnightDust/PictureSign#13]
This may sound like it's not a problem, however due to the default keybind being set to "C", it also breaks any other keybinds (such as zoom) that may be set to C.

**Comment by Hendrix-Shen** [comment]
I think you should enable debug mode in the PictureSign settings and restart the game.

**Comment by EvionFox** [comment]
Unfortunately I'm running into this as well. I don't use MultiMC, but anything that I bind to C doesn't work when I have PictureSign installed. This includes when it is set to Debug mode.

**Comment by Motschen** [comment]
Removed in later versions of the mod.
In older versions, you can change the keybinding after enabling debug mode in the config and restarting your game.
