### ISSUE TITLE
Not working MP? 1.19.2

### ISSUE THREAD

**Issue by Wubzzz1337** [TeamMidnightDust/PictureSign#20]
Hey, I don't get any error or anything.

It just doesn't display it on MP but it works on SP.

SP:
![image](https://user-images.githubusercontent.com/114503915/224133409-cdcddbba-02a7-45cc-94af-7987b35f2340.png)
MP:
![image](https://user-images.githubusercontent.com/114503915/224133558-1d9b8150-3e21-4a0a-8433-55c78174f635.png)

**Comment by Wubzzz1337** [comment]
It seems the formatting "5:2:::" is what causes this, but this only happens on MP servers, not on SP worlds.
It is not done by me but by the mod itself it seems.

**Comment by Motschen** [comment]
Make sure to click in every text field after putting in the link.
This is a known bug and is already fixed in an unreleased version (one that also adds support for video playback, btw ;)
