### ISSUE TITLE
[1.19.2] No images rendered (fixed; error notifier suggestion)

### ISSUE THREAD

**Issue by esotericdesign** [TeamMidnightDust/PictureSign#25]
I'm using imgur links, both with and without helper GUI, images just don't render.

Mods present:
Picture Sign ver. 1.4.1
Fabric API ver. 0.77.0
Smooth Boot ver. 1.7.1

**Comment by esotericdesign** [comment]
UPD: Mod **is** working, it was Imgur that did not.
Suggestion: an error message in the chat or above sign to better understand where the problem is

**Comment by Motschen** [comment]
I added the error message feature in 2.0.0 :)
