### ISSUE TITLE
Nightmare Edge Case: x86 installed on an ARM Mac will crash the game at launch

### ISSUE THREAD

**Issue by LemmaEOF** [TeamMidnightDust/PictureSign#26]
Log: https://mclo.gs/UXB22Gg

From what I can tell this is because the backend grabbing libvlc will assume that it's the ARM version and not check whether it's x86 or ARM; I'm not sure if there's a good way to deal with this lol

**Comment by LemmaEOF** [comment]
This has also been posted as a watermedia issue ([#89](https://github.com/WaterMediaTeam/watermedia/issues/89)) but it might be good to check for that crash on the picturesign side if possible

**Comment by SrRapero720** [comment]
i always suggest install universal version of VLC when _you have no idea_
https://get.videolan.org/vlc/3.0.21/macosx/vlc-3.0.21-universal.dmg

whoever, those crashes should not be a throwed crash (referencing https://github.com/WaterMediaTeam/watermedia/commit/366ccaee8929a284093e573caac23048481680a2), so i need to do some research of what happens (or what is not happening)

**Comment by SrRapero720** [comment]
ah yes... the special vlccore load, i forgot was a thing on mac :/

**Comment by LemmaEOF** [comment]
> i always suggest install universal version of VLC when _you have no idea_ https://get.videolan.org/vlc/3.0.21/macosx/vlc-3.0.21-universal.dmg

oh yeah, to be clear I'd installed VLC on an old x86 mac then forgot to update it when I transferred everything to my new ARM one

**Comment by Motschen** [comment]
It seems like SrRapero released an updated version of WATERMeDIA to address this.
This is not something I can fix from the PictureSign side, as I only interface with WATERMeDIA and don't interfere in the VLC initialization.

**Comment by Motschen** [comment]
Btw, @LemmaEOF have a look at #23 and [PictureSignTheora](https://github.com/TeamMidnightDust/PictureSignTheora).
I turned una's native Java codec implementation into a version-agnostic addon in the hope to relieve some stress from the Modfest organisors.
