### ISSUE TITLE
PictureSign references internal Iris interfaces

### ISSUE THREAD

**Issue by coderbot16** [TeamMidnightDust/PictureSign#8]
Please use the Iris API (net.irisshaders.api) instead.

https://github.com/TeamMidnightDust/PictureSign/blob/b3249b9664854fb7e8288c96f466491efdf27fa0/src/main/java/eu/midnightdust/picturesign/render/PictureSignRenderer.java#L100

**Comment by leonpano2006** [comment]
> Please use the Iris API (net.irisshaders.api) instead.
> 
> 
> 
> https://github.com/TeamMidnightDust/PictureSign/blob/b3249b9664854fb7e8288c96f466491efdf27fa0/src/main/java/eu/midnightdust/picturesign/render/PictureSignRenderer.java#L100

You can close now
That is in 1.3.0 update
